language: c
compiler: clang
branches:
    only:
        - master
os:
    - linux
    - osx
sudo: false
addons:
    apt:
        packages:
            - cmake
script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
